import type { Product, Category, Order, Review } from './types';

export const categories: Category[] = [
  { id: 'electronics', name: 'Electronics' },
  { id: 'apparel', name: 'Apparel' },
  { id: 'books', name: 'Books' },
  { id: 'home-goods', name: 'Home Goods' },
  { id: 'accessories', name: 'Accessories' },
  { id: 'footwear', name: 'Footwear' },
];

const productReviews: { [key: string]: Review[] } = {
  '1': [
    {
      id: 'rev1',
      author: 'Alice Johnson',
      avatar: 'https://placehold.co/100x100.png',
      rating: 5,
      title: 'Absolutely fantastic!',
      content: 'The sound quality is crisp and clear, and the noise cancellation is a game-changer. They are also incredibly comfortable for long listening sessions. Worth every penny!',
      date: '2024-05-22',
    },
    {
      id: 'rev2',
      author: 'Mark Roberts',
      avatar: 'https://placehold.co/100x100.png',
      rating: 4,
      title: 'Great headphones, solid performance',
      content: "Really happy with this purchase. The battery life is impressive, and they connect to my devices seamlessly. My only small gripe is they feel a bit tight after several hours of use.",
      date: '2024-05-18',
    },
  ],
  '2': [
     {
      id: 'rev3',
      author: 'David Chen',
      avatar: 'https://placehold.co/100x100.png',
      rating: 5,
      title: 'Perfect fit and quality',
      content: 'This t-shirt is made from high-quality cotton and fits perfectly. It has held up well after multiple washes. A great staple for any wardrobe.',
      date: '2024-05-20',
    }
  ],
  '5': [
     {
      id: 'rev4',
      author: 'Emily White',
      avatar: 'https://placehold.co/100x100.png',
      rating: 5,
      title: 'The most comfortable yoga pants ever',
      content: "These are so soft and stretchy, it feels like I'm wearing nothing. They are not see-through at all, even during deep squats. I'm buying another pair in a different color!",
      date: '2024-05-25',
    },
  ],
  '7': [
     {
      id: 'rev5',
      author: 'Sophia Brown',
      avatar: 'https://placehold.co/100x100.png',
      rating: 5,
      title: 'Life-changing book',
      content: "This book provides practical and actionable steps to build better habits. It's well-researched and easy to read. I've already started implementing its principles in my daily life.",
      date: '2024-05-21',
    },
  ]
};


export const products: Product[] = [
  {
    id: '1',
    name: 'Wireless Bluetooth Headphones',
    description: 'High-fidelity wireless headphones with noise-cancellation and a 20-hour battery life. Perfect for music lovers and commuters.',
    price: 99.99,
    originalPrice: 129.99,
    badge: 'Sale',
    image: 'https://placehold.co/600x600.png',
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x400.png', 'https://placehold.co/400x600.png', 'https://placehold.co/600x600.png'],
    categoryId: 'electronics',
    featured: true,
    rating: 4.5,
    reviews: productReviews['1'],
  },
  {
    id: '2',
    name: 'Men\'s Classic T-Shirt',
    description: 'A comfortable and stylish 100% cotton t-shirt. Available in various colors and sizes. A wardrobe essential.',
    price: 19.99,
    image: 'https://placehold.co/600x600.png',
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    categoryId: 'apparel',
    featured: true,
    rating: 4.8,
    reviews: productReviews['2'],
  },
  {
    id: '3',
    name: 'The Midnight Library',
    description: 'A novel by Matt Haig, exploring the choices that go into a life well lived. A Sunday Times bestseller.',
    price: 14.50,
    originalPrice: 20.00,
    badge: '15% Off',
    image: 'https://placehold.co/600x600.png',
    images: ['https://placehold.co/600x600.png'],
    categoryId: 'books',
    featured: false,
    rating: 4.6,
    reviews: productReviews['3'],
  },
  {
    id: '4',
    name: 'Smart Home Hub',
    description: 'Control all your smart devices from one central hub. Compatible with Alexa, Google Assistant, and Apple HomeKit.',
    price: 129.00,
    image: 'https://placehold.co/600x600.png',
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    categoryId: 'electronics',
    featured: false,
    rating: 4.7,
    reviews: productReviews['4'],
  },
  {
    id: '5',
    name: 'Women\'s Yoga Pants',
    description: 'High-waisted, buttery soft yoga pants perfect for workouts or lounging. Breathable and moisture-wicking fabric.',
    price: 49.99,
    badge: 'New',
    image: 'https://placehold.co/600x600.png',
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    categoryId: 'apparel',
    featured: true,
    rating: 4.9,
    reviews: productReviews['5'],
  },
  {
    id: '6',
    name: 'Scented Soy Candle',
    description: 'Hand-poured soy wax candle with a calming lavender scent. 40-hour burn time. Perfect for creating a relaxing atmosphere.',
    price: 24.99,
    originalPrice: 29.99,
    badge: 'Sale',
    image: 'https://placehold.co/600x600.png',
    images: ['https://placehold.co/600x600.png'],
    categoryId: 'home-goods',
    featured: false,
    rating: 4.8,
    reviews: productReviews['6'],
  },
  {
    id: '7',
    name: 'Atomic Habits',
    description: 'An easy & proven way to build good habits & break bad ones by James Clear. A #1 New York Times bestseller.',
    price: 16.99,
    image: 'https://placehold.co/600x600.png',
    images: ['https://placehold.co/600x600.png'],
    categoryId: 'books',
    featured: true,
    rating: 4.9,
    reviews: productReviews['7'],
  },
  {
    id: '8',
    name: 'Kitchen Stand Mixer',
    description: 'Powerful 10-speed stand mixer for all your baking needs. Includes a 5-quart stainless steel bowl, flat beater, dough hook, and wire whip.',
    price: 249.99,
    image: 'https://placehold.co/600x600.png',
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    categoryId: 'home-goods',
    featured: false,
    rating: 4.7,
    reviews: productReviews['8'],
  },
];

export const featuredProducts = products.filter(p => p.featured);

export const orders: Order[] = [
    {
      id: 'ORD001',
      date: '2023-10-26',
      status: 'Delivered',
      total: 119.98,
      items: [
        { product: products[0], quantity: 1 },
        { product: products[1], quantity: 1 },
      ],
    },
    {
      id: 'ORD002',
      date: '2023-10-28',
      status: 'Shipped',
      total: 49.99,
      items: [{ product: products[4], quantity: 1 }],
    },
    {
      id: 'ORD003',
      date: '2023-11-01',
      status: 'Processing',
      total: 16.99,
      items: [{ product: products[6], quantity: 1 }],
    },
  ];
